# permissions for end users to view forecastpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: scalepilot
    app.kubernetes.io/managed-by: kustomize
  name: forecastpolicy-viewer-role
rules:
- apiGroups:
  - autoscaling.scalepilot.io
  resources:
  - forecastpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling.scalepilot.io
  resources:
  - forecastpolicies/status
  verbs:
  - get
