---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.scalepilot.io
  resources:
  - clusterscaleprofiles
  - federatedscaledobjects
  - forecastpolicies
  - scalingbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.scalepilot.io
  resources:
  - clusterscaleprofiles/finalizers
  - federatedscaledobjects/finalizers
  - forecastpolicies/finalizers
  - scalingbudgets/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.scalepilot.io
  resources:
  - clusterscaleprofiles/status
  - federatedscaledobjects/status
  - forecastpolicies/status
  - scalingbudgets/status
  verbs:
  - get
  - patch
  - update
