## Append samples of your project ##
resources:
- autoscaling_v1alpha1_forecastpolicy.yaml
- autoscaling_v1alpha1_federatedscaledobject.yaml
- autoscaling_v1alpha1_scalingbudget.yaml
- autoscaling_v1alpha1_clusterscaleprofile.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
