//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ARIMAParams) DeepCopyInto(out *ARIMAParams) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ARIMAParams.
func (in *ARIMAParams) DeepCopy() *ARIMAParams {
	if in == nil {
		return nil
	}
	out := new(ARIMAParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlackoutWindow) DeepCopyInto(out *BlackoutWindow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlackoutWindow.
func (in *BlackoutWindow) DeepCopy() *BlackoutWindow {
	if in == nil {
		return nil
	}
	out := new(BlackoutWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudCostConfig) DeepCopyInto(out *CloudCostConfig) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudCostConfig.
func (in *CloudCostConfig) DeepCopy() *CloudCostConfig {
	if in == nil {
		return nil
	}
	out := new(CloudCostConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRef) DeepCopyInto(out *ClusterRef) {
	*out = *in
	out.SecretRef = in.SecretRef
	if in.MaxCapacity != nil {
		in, out := &in.MaxCapacity, &out.MaxCapacity
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRef.
func (in *ClusterRef) DeepCopy() *ClusterRef {
	if in == nil {
		return nil
	}
	out := new(ClusterRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterScaleProfile) DeepCopyInto(out *ClusterScaleProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterScaleProfile.
func (in *ClusterScaleProfile) DeepCopy() *ClusterScaleProfile {
	if in == nil {
		return nil
	}
	out := new(ClusterScaleProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterScaleProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterScaleProfileList) DeepCopyInto(out *ClusterScaleProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterScaleProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterScaleProfileList.
func (in *ClusterScaleProfileList) DeepCopy() *ClusterScaleProfileList {
	if in == nil {
		return nil
	}
	out := new(ClusterScaleProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterScaleProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterScaleProfileSpec) DeepCopyInto(out *ClusterScaleProfileSpec) {
	*out = *in
	if in.BlackoutWindows != nil {
		in, out := &in.BlackoutWindows, &out.BlackoutWindows
		*out = make([]BlackoutWindow, len(*in))
		copy(*out, *in)
	}
	if in.TeamOverrides != nil {
		in, out := &in.TeamOverrides, &out.TeamOverrides
		*out = make([]TeamOverride, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterScaleProfileSpec.
func (in *ClusterScaleProfileSpec) DeepCopy() *ClusterScaleProfileSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterScaleProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterScaleProfileStatus) DeepCopyInto(out *ClusterScaleProfileStatus) {
	*out = *in
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterScaleProfileStatus.
func (in *ClusterScaleProfileStatus) DeepCopy() *ClusterScaleProfileStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterScaleProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederatedScaledObject) DeepCopyInto(out *FederatedScaledObject) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederatedScaledObject.
func (in *FederatedScaledObject) DeepCopy() *FederatedScaledObject {
	if in == nil {
		return nil
	}
	out := new(FederatedScaledObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FederatedScaledObject) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederatedScaledObjectList) DeepCopyInto(out *FederatedScaledObjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FederatedScaledObject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederatedScaledObjectList.
func (in *FederatedScaledObjectList) DeepCopy() *FederatedScaledObjectList {
	if in == nil {
		return nil
	}
	out := new(FederatedScaledObjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FederatedScaledObjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederatedScaledObjectSpec) DeepCopyInto(out *FederatedScaledObjectSpec) {
	*out = *in
	in.PrimaryCluster.DeepCopyInto(&out.PrimaryCluster)
	if in.OverflowClusters != nil {
		in, out := &in.OverflowClusters, &out.OverflowClusters
		*out = make([]ClusterRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Metric = in.Metric
	out.Workload = in.Workload
	if in.MaxTotalReplicas != nil {
		in, out := &in.MaxTotalReplicas, &out.MaxTotalReplicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederatedScaledObjectSpec.
func (in *FederatedScaledObjectSpec) DeepCopy() *FederatedScaledObjectSpec {
	if in == nil {
		return nil
	}
	out := new(FederatedScaledObjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederatedScaledObjectStatus) DeepCopyInto(out *FederatedScaledObjectStatus) {
	*out = *in
	if in.OverflowClusters != nil {
		in, out := &in.OverflowClusters, &out.OverflowClusters
		*out = make([]OverflowClusterStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastScaleTime != nil {
		in, out := &in.LastScaleTime, &out.LastScaleTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederatedScaledObjectStatus.
func (in *FederatedScaledObjectStatus) DeepCopy() *FederatedScaledObjectStatus {
	if in == nil {
		return nil
	}
	out := new(FederatedScaledObjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForecastPolicy) DeepCopyInto(out *ForecastPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForecastPolicy.
func (in *ForecastPolicy) DeepCopy() *ForecastPolicy {
	if in == nil {
		return nil
	}
	out := new(ForecastPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ForecastPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForecastPolicyList) DeepCopyInto(out *ForecastPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ForecastPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForecastPolicyList.
func (in *ForecastPolicyList) DeepCopy() *ForecastPolicyList {
	if in == nil {
		return nil
	}
	out := new(ForecastPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ForecastPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForecastPolicySpec) DeepCopyInto(out *ForecastPolicySpec) {
	*out = *in
	out.TargetDeployment = in.TargetDeployment
	out.TargetHPA = in.TargetHPA
	out.MetricSource = in.MetricSource
	if in.ARIMAParams != nil {
		in, out := &in.ARIMAParams, &out.ARIMAParams
		*out = new(ARIMAParams)
		**out = **in
	}
	if in.HoltWintersParams != nil {
		in, out := &in.HoltWintersParams, &out.HoltWintersParams
		*out = new(HoltWintersParams)
		**out = **in
	}
	if in.MaxReplicaCap != nil {
		in, out := &in.MaxReplicaCap, &out.MaxReplicaCap
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForecastPolicySpec.
func (in *ForecastPolicySpec) DeepCopy() *ForecastPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ForecastPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForecastPolicyStatus) DeepCopyInto(out *ForecastPolicyStatus) {
	*out = *in
	if in.LastTrainedAt != nil {
		in, out := &in.LastTrainedAt, &out.LastTrainedAt
		*out = (*in).DeepCopy()
	}
	if in.PredictedMinReplicas != nil {
		in, out := &in.PredictedMinReplicas, &out.PredictedMinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.ActiveMinReplicas != nil {
		in, out := &in.ActiveMinReplicas, &out.ActiveMinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForecastPolicyStatus.
func (in *ForecastPolicyStatus) DeepCopy() *ForecastPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ForecastPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HoltWintersParams) DeepCopyInto(out *HoltWintersParams) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HoltWintersParams.
func (in *HoltWintersParams) DeepCopy() *HoltWintersParams {
	if in == nil {
		return nil
	}
	out := new(HoltWintersParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationConfig) DeepCopyInto(out *NotificationConfig) {
	*out = *in
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(SlackNotification)
		**out = **in
	}
	if in.PagerDuty != nil {
		in, out := &in.PagerDuty, &out.PagerDuty
		*out = new(PagerDutyNotification)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationConfig.
func (in *NotificationConfig) DeepCopy() *NotificationConfig {
	if in == nil {
		return nil
	}
	out := new(NotificationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OverflowClusterStatus) DeepCopyInto(out *OverflowClusterStatus) {
	*out = *in
	if in.LastProbeTime != nil {
		in, out := &in.LastProbeTime, &out.LastProbeTime
		*out = (*in).DeepCopy()
	}
	if in.LastSpillTime != nil {
		in, out := &in.LastSpillTime, &out.LastSpillTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OverflowClusterStatus.
func (in *OverflowClusterStatus) DeepCopy() *OverflowClusterStatus {
	if in == nil {
		return nil
	}
	out := new(OverflowClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagerDutyNotification) DeepCopyInto(out *PagerDutyNotification) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagerDutyNotification.
func (in *PagerDutyNotification) DeepCopy() *PagerDutyNotification {
	if in == nil {
		return nil
	}
	out := new(PagerDutyNotification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusMetricSource) DeepCopyInto(out *PrometheusMetricSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusMetricSource.
func (in *PrometheusMetricSource) DeepCopy() *PrometheusMetricSource {
	if in == nil {
		return nil
	}
	out := new(PrometheusMetricSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingBudget) DeepCopyInto(out *ScalingBudget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingBudget.
func (in *ScalingBudget) DeepCopy() *ScalingBudget {
	if in == nil {
		return nil
	}
	out := new(ScalingBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalingBudget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingBudgetList) DeepCopyInto(out *ScalingBudgetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScalingBudget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingBudgetList.
func (in *ScalingBudgetList) DeepCopy() *ScalingBudgetList {
	if in == nil {
		return nil
	}
	out := new(ScalingBudgetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalingBudgetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingBudgetSpec) DeepCopyInto(out *ScalingBudgetSpec) {
	*out = *in
	out.CloudCost = in.CloudCost
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = new(NotificationConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingBudgetSpec.
func (in *ScalingBudgetSpec) DeepCopy() *ScalingBudgetSpec {
	if in == nil {
		return nil
	}
	out := new(ScalingBudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingBudgetStatus) DeepCopyInto(out *ScalingBudgetStatus) {
	*out = *in
	if in.LastCheckedAt != nil {
		in, out := &in.LastCheckedAt, &out.LastCheckedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingBudgetStatus.
func (in *ScalingBudgetStatus) DeepCopy() *ScalingBudgetStatus {
	if in == nil {
		return nil
	}
	out := new(ScalingBudgetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackNotification) DeepCopyInto(out *SlackNotification) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackNotification.
func (in *SlackNotification) DeepCopy() *SlackNotification {
	if in == nil {
		return nil
	}
	out := new(SlackNotification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpilloverMetric) DeepCopyInto(out *SpilloverMetric) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpilloverMetric.
func (in *SpilloverMetric) DeepCopy() *SpilloverMetric {
	if in == nil {
		return nil
	}
	out := new(SpilloverMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetDeploymentRef) DeepCopyInto(out *TargetDeploymentRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetDeploymentRef.
func (in *TargetDeploymentRef) DeepCopy() *TargetDeploymentRef {
	if in == nil {
		return nil
	}
	out := new(TargetDeploymentRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetHPARef) DeepCopyInto(out *TargetHPARef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetHPARef.
func (in *TargetHPARef) DeepCopy() *TargetHPARef {
	if in == nil {
		return nil
	}
	out := new(TargetHPARef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamOverride) DeepCopyInto(out *TeamOverride) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaxSurgePercent != nil {
		in, out := &in.MaxSurgePercent, &out.MaxSurgePercent
		*out = new(int32)
		**out = **in
	}
	if in.AllowedAlgorithms != nil {
		in, out := &in.AllowedAlgorithms, &out.AllowedAlgorithms
		*out = make([]ForecastAlgorithm, len(*in))
		copy(*out, *in)
	}
	if in.MaxReplicasPerDeployment != nil {
		in, out := &in.MaxReplicasPerDeployment, &out.MaxReplicasPerDeployment
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamOverride.
func (in *TeamOverride) DeepCopy() *TeamOverride {
	if in == nil {
		return nil
	}
	out := new(TeamOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadTemplate) DeepCopyInto(out *WorkloadTemplate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadTemplate.
func (in *WorkloadTemplate) DeepCopy() *WorkloadTemplate {
	if in == nil {
		return nil
	}
	out := new(WorkloadTemplate)
	in.DeepCopyInto(out)
	return out
}
